EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Controllers/RatePlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using EasyGasAdminWebsite.Configuration;
using EasyGasAdminWebsite.Extensions;
using EasyGasAdminWebsite.Models;
using EasyGasAdminWebsite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace EasyGasAdminWebsite.Controllers
{
    [Authorize]
    public class RatePlanController : BaseController
    {
        private readonly IRatePlanService _rateplanServices;
        private readonly IOptions<ApiSettings> _apiSettings;
        public RatePlanController(IRatePlanService rateplanService, IOptions<ApiSettings> apiSettings, UserManager<ApplicationUser> userManager, IHttpContextAccessor httpContextAccessor) : base(userManager, httpContextAccessor)
        {
            _rateplanServices = rateplanService;
            _apiSettings = apiSettings;
        }

        public async Task<IActionResult> Index(int page)
        {
            var branchId = await GetCurrentUserBranchId();
            var tenantId = await GetCurrentUserTenantId();
            List<ItemPricing> list = new List<ItemPricing>();
            list = await _rateplanServices.GetListAsync(tenantId, branchId, null);
            ViewBag.list = list;
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var branchId = await GetCurrentUserBranchId();
            var tenantId = await GetCurrentUserTenantId();
            ItemPricing pricing = new ItemPricing() { FromDate = DateMgr.GetCurrentIndiaTime() };
            CreatePricingPageModel createPageModel = await _rateplanServices.GetCreatePricingPageModel(tenantId, branchId, null);
            //ViewBag.createPageModel = createPageModel;
            ViewBag.itemSelList = new SelectList(new List<Item>() , "Id", "Name");
            if (createPageModel.ItemList != null)
            {
                if (createPageModel.ItemList.Count > 0)
                {
                    List<Item> cylList = createPageModel.ItemList.Where(p => p.Category == ItemCategory.Cylinder && p.Type == ItemType.Physical).ToList();
                    ViewBag.itemSelList = new SelectList(cylList, "Id", "Name");
                }
            }
            
            //ViewBag.tenantSelList = new SelectList(createPageModel.TenantList, "TenantId", "Name");
            ApiValidationErrors responseMsg = new ApiValidationErrors() { };
            responseMsg.Err = new string[0];
            ViewBag.source = "Create";
            ViewBag.responseMsg = responseMsg;
            return View(pricing);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ItemPricing pricing, string submitButton)
        {
            var branchId = await GetCurrentUserBranchId();
            var tenantId = await GetCurrentUserTenantId();
            ApiValidationErrors responseMsg = new ApiValidationErrors { Err = new string[0] };
            if (ModelState.IsValid)
            {
                var result = await _rateplanServices.CreatePricingAsync(pricing);
                if (result.IsSuccessStatusCode)
                {
                    if (submitButton == "1")
                    {
                        return Redirect("Create");
                    }
                    else if (submitButton == "2")
                    {
                        return Redirect("Index");
                    }
                     {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                }
                else
                {
                    if (result.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var responseJson = await result.Content.ReadAsStringAsync();
                        responseMsg = JsonConvert.DeserializeObject<ApiValidationErrors>(responseJson);
                    }
                    if (responseMsg.Err == null)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                    else if (responseMsg.Err.Length == 0)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                }
            }
            ViewBag.responseMsg = responseMsg;
            CreatePricingPageModel createPageModel = await _rateplanServices.GetCreatePricingPageModel(tenantId, branchId, null); 
            //ViewBag.createPageModel = createPageModel;
            ViewBag.source = "Create";
            ViewBag.itemSelList = new SelectList(new List<Item>(), "Id", "Name");
            if (createPageModel.ItemList != null)
            {
                if (createPageModel.ItemList.Count > 0)
                {
                    List<Item> cylList = createPageModel.ItemList.Where(p => p.Category == ItemCategory.Cylinder).ToList();
                    ViewBag.itemSelList = new SelectList(cylList, "Id", "Name");
                }
            }
            return View(pricing);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var branchId = await GetCurrentUserBranchId();
            var tenantId = await GetCurrentUserTenantId();
            ItemPricing pricing = new ItemPricing() { FromDate = DateMgr.GetCurrentIndiaTime() };
            CreatePricingPageModel createPageModel = await _rateplanServices.GetCreatePricingPageModel(tenantId, branchId, id);
            //ViewBag.createPageModel = createPageModel;
            ViewBag.itemSelList = new SelectList(new List<Item>(), "Id", "Name");
            if (createPageModel.ItemList != null)
            {
                if (createPageModel.ItemList.Count > 0)
                {
                    List<Item> cylList = createPageModel.ItemList.Where(p => p.Category == ItemCategory.Cylinder).ToList();
                    ViewBag.itemSelList = new SelectList(cylList, "Id", "Name");
                }
            }
            if (createPageModel.PricingModel != null)
            {
                pricing = createPageModel.PricingModel;
            }
            //ViewBag.tenantSelList = new SelectList(createPageModel.TenantList, "TenantId", "Name");
            ApiValidationErrors responseMsg = new ApiValidationErrors() { };
            responseMsg.Err = new string[0];
            ViewBag.source = "Edit";
            ViewBag.responseMsg = responseMsg;
            return View("Create", pricing);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ItemPricing pricing, string submitButton)
        {
            var branchId = await GetCurrentUserBranchId();
            var tenantId = await GetCurrentUserTenantId();
            ApiValidationErrors responseMsg = new ApiValidationErrors { Err = new string[0] };

            if (ModelState.IsValid && pricing.Id > 0)
            {
                var result = await _rateplanServices.CreatePricingAsync(pricing);
                if (result.IsSuccessStatusCode)
                {
                    if (submitButton == "1")
                    {
                        return Redirect("Create");
                    }
                    else if (submitButton == "2")
                    {
                        return Redirect("Index");
                    }
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                }
                else
                {
                    if (result.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var responseJson = await result.Content.ReadAsStringAsync();
                        responseMsg = JsonConvert.DeserializeObject<ApiValidationErrors>(responseJson);
                    }
                    if (responseMsg.Err == null)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                    else if (responseMsg.Err.Length == 0)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                }
            }
            ViewBag.responseMsg = responseMsg;
            CreatePricingPageModel createPageModel = await _rateplanServices.GetCreatePricingPageModel(tenantId, branchId, null);
            //ViewBag.createPageModel = createPageModel;
            ViewBag.itemSelList = new SelectList(new List<Item>(), "Id", "Name");
            if (createPageModel.ItemList != null)
            {
                if (createPageModel.ItemList.Count > 0)
                {
                    List<Item> cylList = createPageModel.ItemList.Where(p => p.Category == ItemCategory.Cylinder).ToList();
                    ViewBag.itemSelList = new SelectList(cylList, "Id", "Name");
                }
            }
            ViewBag.source = "Edit";
            return View("Create", pricing);
        }
    }
}

EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Views/RatePlan/Create.cshtml
@model EasyGasAdminWebsite.Models.ItemPricing
@addTagHelper *, EasyGasAdminWebsite
@{
    ViewData["Title"] = ViewBag.source + " Pricing";
    EasyGasAdminWebsite.Models.ApiValidationErrors responseMsg = ViewBag.responseMsg;
    SelectList itemSelList = ViewBag.itemSelList;
}
<style>
</style>
<div class="content-wrapper">
    <section class="content-header">
        <h1>@ViewData["Title"]</h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="@Url.Action("Index", "RatePlan")"><i class="fa fa-dashboard"></i>Rate Plan</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-6">
                <div id="create-order-box" class="box box-danger">
                    @using (Html.BeginForm())
                    {
                        <div class="box-body">
                            <div id="create-order" class="row">
                                <div class="col-md-12">
                                    @if (responseMsg.Err.Length > 0)
                                    {
                                        <div class="validation-summary-errors alert alert-danger-light">
                                            <p>Please correct the following errors</p>
                                            <ul class="validation-summary-errors">
                                                @foreach (string err in responseMsg.Err)
                                                {
                                                    <li>@err</li>
                                                }
                                            </ul>
                                        </div>
                                    }


                                    @Html.AntiForgeryToken()
                                    @Html.HiddenFor(model => model.Id, new { @id = "pricingId" })


                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="ItemId" class="control-label"></label>
                                                <select asp-for="ItemId" asp-items="@itemSelList" class="form-control">
                                                    <option value="">Select</option>
                                                </select>
                                                @Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="FromDate" class="control-label"></label>
                                                @Html.TextBoxFor(model => model.FromDate, new { @class = "form-control", @placeholder = "dd/mm/yyyy" })
                                                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="Price" class="control-label"></label>
                                                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="InternationalPrice" class="control-label"></label>
                                                @Html.EditorFor(model => model.InternationalPrice, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.InternationalPrice, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="row">
                                <div class="col-md-12">
                                    @if (ViewBag.source == "Edit")
                                    {
                                        <button class="btn btn-primary btn-lg" name="submitButton" value="2" style="margin-right: 10px;">Save</button>
                                    }
                                    else
                                    {
                                        <button class="btn btn-primary btn-lg" name="submitButton" value="1" style="margin-right: 10px;">Save and Create</button>
                                        <button class="btn btn-default btn-lg" name="submitButton" value="2">Save and Exit</button>
                                    }
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</div>


<script>
    $(document).ready(function () {
        $("#FromDate").datetimepicker({ format: "DD/MM/YYYY" });
    })
</script>

EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Views/RatePlan/Index.cshtml
@{
    ViewData["Title"] = "Rate Plan";
    List<EasyGasAdminWebsite.Models.ItemPricing> list = ViewBag.list;
}

<div class="content-wrapper">
    @*<section class="content-header">
            <h1>@ViewData["Title"]</h1>
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Home", "Index")"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">@ViewData["Title"]</li>
            </ol>
        </section>*@
    <section class="content">
        <div class="row">
            <div class="col-xs-8">
                <div class="box box-danger">
                    <div class="box-header with-border">
                        <h3 class="box-title">Rate Plan <a href="@Url.Action("Create")" style="margin-left: 10px;" class="btn btn-primary btn-sm"><i class="fa fa-plus" style="margin-right:5px;"></i> Create New</a></h3>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table id="pricingList" class="table table-hover table-striped">
                                    <thead>
                                        <tr>
                                            <th>S No</th>
                                            <th>Item</th>
                                            <th>From Date</th>
                                            <th>Price</th>
                                            <th>International Price</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in list)
                                        {

                                        <tr data-pricing_id="@item.Id">
                                            <td></td>
                                            <td>@item.Item.Name</td>
                                            <td>@item.FromDate.ToString("dd/MM/yyyy")</td>
                                            <td>@item.Price</td>
                                            <td>@item.InternationalPrice</td>
                                            <td><a class="btn btn-primary" href="@Url.Action("Edit", "RatePlan", new {id = item.Id })">Edit</a></td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<script>
    var orderDataTable = $("#pricingList").DataTable({
        'paging': true,
        'lengthChange': true,
        'searching': true,
        'ordering': true,
        'info': true,
        'autoWidth': true,
        //'columnDefs': [{ orderable: false, targets: [-1, -2] }],
        'language': {
            'emptyTable': 'No rate plans found.'
        },
        "fnRowCallback": function (nRow, aData, iDisplayIndex) {
            $("td:first", nRow).html(iDisplayIndex + 1);
            return nRow;
        },
    })


</script>