EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Models/Driver.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EasyGasAdminWebsite.Models
{
    public class Driver
    {
        public UserAndProfileModel UserProfile { get; set; }

    }

    public enum DLoginState
    {
        LoggedIN,
        PauseJob,
        Resume,
        LoggedOut,
    }

    public enum DActivityState
    {
        NoJob,
        HasJob,
        DisplayedJob,
        OrderVerification,
        PauseJob,
        BacktoJob,
        TripStarted,
        DirectionInMaps,
        TripDeliverd,
        FeedbackCaptured
    }

    public class DriverOrderSummaryVM
    {
        public int DriverId { get; set; }
        public string DriverName { get; set; }
        public int VehicleId { get; set; }
        public string VehicleName { get; set; }
        public string TenantName { get; set; }
        public string BranchName { get; set; }
        public int OrdersDelivered { get; set; }
        public int OrdersMissed { get; set; }
        public long TravelledMeters { get; set; }
        public long ActiveTimeInMin { get; set; }
        public float RewardPoints { get; set; }

        //universally accepted time format 
        public long StartPeriodUAT { get; set; }
        public long EndPeriodUAT { get; set; }

        public float CashCollected { get; set; }
        public float DaysWorked { get; set; }
        public DLoginState Dls { get; set; }
        public DateTime DlsTime { get; set; }
        public int DlsTimeAgo { get; set; }
        public DActivityState Das { get; set; }
        public DateTime DasTime { get; set; }
        public int DasTimeAgo { get; set; }
    }
}

EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Controllers/DriversController.cs
using EasyGasAdminWebsite.Configuration;
using EasyGasAdminWebsite.Models;
using EasyGasAdminWebsite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace EasyGasAdminWebsite.Controllers
{
    [Authorize]
    public class DriversController : BaseController
    {
        private readonly IDriverService _driverServices;
        private readonly IOptions<ApiSettings> _apiSettings;
        public DriversController(IDriverService driverServices, IOptions<ApiSettings> apiSettings, UserManager<ApplicationUser> userManager, IHttpContextAccessor httpContextAccessor) : base(userManager, httpContextAccessor)
        {
            _driverServices = driverServices;
            _apiSettings = apiSettings;
        }
        public async Task<IActionResult> Index()
        {
            int tenantId = await GetCurrentUserTenantId();
            int? branchId = await GetCurrentUserBranchId();
            Models.DriverViewModels.IndexPageModel indexModel = new Models.DriverViewModels.IndexPageModel();
            indexModel = await _driverServices.GetIndexPageModel(tenantId, branchId);
            ViewBag.driversList = indexModel.DriverList;
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> View(int id)
        {
            var userWithDetails = await _driverServices.GetDriverDetails(id);
            if (userWithDetails.UserAndProfile != null)
            {
                return View(userWithDetails);
            }
            else
            {
                throw new Exception("Page not found");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            UserAndProfileModel customer = new UserAndProfileModel() { };
            ApiValidationErrors responseMsg = new ApiValidationErrors() { };
            responseMsg.Err = new string[0];
            ViewBag.responseMsg = responseMsg;
            ViewBag.source = "Create";
            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserAndProfileModel customer)
        {
            int tenantId = await GetCurrentUserTenantId();
            int? branchId = await GetCurrentUserBranchId();
            ApiValidationErrors responseMsg = new ApiValidationErrors { Err = new string[0] };
            customer.TenantId = tenantId;
            customer.BranchId = branchId;
            customer.Type = UserType.DRIVER;
            if (ModelState.IsValid)
            {
                var result = await _driverServices.CreateDriverAsync(customer);
                if (result.IsSuccessStatusCode)
                {
                    return Redirect("Index");
                }
                else
                {
                    if (result.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var responseJson = await result.Content.ReadAsStringAsync();
                        responseMsg = JsonConvert.DeserializeObject<ApiValidationErrors>(responseJson);
                    }
                    if (responseMsg.Err == null)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                    else if (responseMsg.Err.Length == 0)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                }
            }
            ViewBag.responseMsg = responseMsg;
            ViewBag.source = "Create";
            return View(customer);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var userWithDetails = await _driverServices.GetDriverDetails(id);
            UserAndProfileModel customer = userWithDetails.UserAndProfile;
            ApiValidationErrors responseMsg = new ApiValidationErrors() { };
            responseMsg.Err = new string[0];
            ViewBag.responseMsg = responseMsg;
            ViewBag.source = "Edit";
            return View("Create", customer);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserAndProfileModel customer)
        {
            ApiValidationErrors responseMsg = new ApiValidationErrors { Err = new string[0] };
            if (ModelState.IsValid && customer.UserId > 0)
            {
                var result = await _driverServices.UpdateDriverAsync(customer);
                if (result.IsSuccessStatusCode)
                {
                    return Redirect("Index");
                }
                else
                {
                    if (result.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var responseJson = await result.Content.ReadAsStringAsync();
                        responseMsg = JsonConvert.DeserializeObject<ApiValidationErrors>(responseJson);
                    }
                    if (responseMsg.Err == null)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                    else if (responseMsg.Err.Length == 0)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                }
            }
            ViewBag.responseMsg = responseMsg;
            ViewBag.source = "Edit";
            return View( "Create", customer);
        }
    }
}

EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Views/Drivers/Create.cshtml
@model EasyGasAdminWebsite.Models.UserAndProfileModel
@addTagHelper *, EasyGasAdminWebsite
@{
    ViewData["Title"] = ViewBag.source + " Driver";
    EasyGasAdminWebsite.Models.ApiValidationErrors responseMsg = ViewBag.responseMsg;
}
<style>
</style>
<div class="content-wrapper">
    <section class="content-header">
        <h1>@ViewData["Title"]</h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="@Url.Action("Index", "Drivers")"><i class="fa fa-dashboard"></i>Drivers</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-6">
                <div id="create-order-box" class="box box-danger">
                    @using (Html.BeginForm())
                    {
                        <div class="box-body">
                            <div id="create-order" class="row">
                                <div class="col-md-12">
                                    @if (responseMsg.Err.Length > 0)
                                    {
                                        <div class="validation-summary-errors alert alert-danger-light">
                                            <p>Please correct the following errors</p>
                                            <ul class="validation-summary-errors">
                                                @foreach (string err in responseMsg.Err)
                                                {
                                                    <li>@err</li>
                                                }
                                            </ul>
                                        </div>
                                    }

                                    @Html.AntiForgeryToken()
                                    @Html.HiddenFor(model => model.UserId, new { @id = "userId" })

                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="FirstName" class="control-label"></label>
                                                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control UserSearch" } })
                                                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="LastName" class="control-label"></label>
                                                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="Gender" class="control-label"></label>
                                                <select asp-for="Gender" asp-items="Html.GetEnumSelectList<Gender>()" class="form-control"></select>
                                                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="Mobile" class="control-label"></label>
                                                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control UserSearch" } })
                                                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="Email" class="control-label"></label>
                                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="BirthDate" class="control-label"></label>
                                                @Html.TextBoxFor(model => model.BirthDate, new { @class = "form-control", @placeholder = "dd/mm/yyyy" })
                                                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="row">
                                <div class="col-md-12">
                                    @if (ViewBag.source == "Edit")
                                    {
                                        <button class="btn btn-primary btn-lg" name="submitButton" style="margin-right: 10px;">Save</button>
                                    }
                                    else
                                    {
                                        <button class="btn btn-primary btn-lg" name="submitButton" value="1" style="margin-right: 10px;">Create</button>
                                    }
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</div>


<script>
    $(document).ready(function () {
        $("#BirthDate").datetimepicker({ format: "DD/MM/YYYY" });
    })
</script>

EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Views/Drivers/Index.cshtml

@{
    ViewData["Title"] = "Drivers";
    List<Driver> driversList = ViewBag.driversList;
}

<style>
    #filters {
        margin-left: 30px;
        display: inline-block;
    }

        #filters .form-group {
            max-width: 320px;
        }

    .select2-container {
        z-index: 99999 !important;
    }

    .popover .select2-container {
        width: 180px !important;
    }

    .select2-container .select2-selection--single {
        height: 32px;
    }

    .popover {
        max-width: 400px !important;
        min-width: 300px;
    }

    .customerName, .vehicleName {
        font-weight: 700;
        cursor: pointer;
    }

    #locations-updatetime {
        font-weight: bold;
    }

    #update-locations i {
        margin-right: 5px;
    }
</style>
<div class="content-wrapper">
    @*<section class="content-header">
            <h1>@ViewData["Title"]</h1>
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Home", "Index")"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">@ViewData["Title"]</li>
            </ol>
        </section>*@
    <section class="content">
        <div class="row">
            <div class="col-xs-8">
                <div class="box box-danger">
                    <div class="box-header with-border">
                        <h3 class="box-title">Drivers <a href="@Url.Action("Create")" style="margin-left: 10px;" class="btn btn-primary btn-sm"><i class="fa fa-plus" style="margin-right:5px;"></i> Create New</a></h3>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table id="driversList" class="table table-hover table-striped">
                                    <thead>
                                        <tr>
                                            <th>S No</th>
                                            <th>Name</th>
                                            <th>Mobile (Username)</th>
                                            <th>Email</th>
                                            <th></th>
                                            @*<th>Birth Date</th>*@
                                        </tr>
                                    </thead>
                                    <tbody>
                                            @foreach (Driver item in driversList)
                                            {

                                                <tr data-driver_id="@item.UserProfile.UserId">
                                                    <td></td>
                                                    <td>@item.UserProfile.FirstName &nbsp; @item.UserProfile.LastName  </td>
                                                    <td>@item.UserProfile.Mobile</td>
                                                    <td>@item.UserProfile.Email</td>
                                                    <td>
                                                        @*<a class="btn btn-primary" href="@Url.Action("View", "Drivers", new {id = item.UserProfile.UserId })">View</a>*@
                                                        <a class="btn btn-primary" href="@Url.Action("Edit", "Drivers", new {id = item.UserProfile.UserId })">Edit</a>
                                                    </td>
                                                    @*<td>@item.UserAndProfile.BirthDate.Value.ToString("dd/MM/yyyy")</td>*@
                                                </tr>
                                            }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<script>
    var customerDataTable = $("#driversList").DataTable({
        'paging': true,
        'lengthChange': true,
        'searching': true,
        'ordering': true,
        'info': true,
        'autoWidth': true,
        'columnDefs': [{ orderable: false, targets: [-1] }],
        'language': {
            'emptyTable': 'No drivers found.'
        },
        "fnRowCallback": function (nRow, aData, iDisplayIndex) {
            $("td:first", nRow).html(iDisplayIndex + 1);
            return nRow;
        },
    })


</script>

EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Views/Drivers/View.cshtml
@model EasyGasAdminWebsite.Models.QueryUserWithDetailsModel
@addTagHelper *, EasyGasAdminWebsite
@{
    ViewData["Title"] = Model.UserAndProfile.FirstName + " " + Model.UserAndProfile.LastName;
}

<div class="content-wrapper">
    <section class="content-header">
        <h1>@ViewData["Title"]</h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="@Url.Action("Index", "Drivers")"><i class="fa fa-dashboard"></i>Drivers</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-danger">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="control-label">Mobile</label>
                                            <div>@Model.UserAndProfile.Mobile</div>
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="control-label">Email</label>
                                            <div>@Model.UserAndProfile.Email</div>
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="control-label">Gender</label>
                                            <div>@Model.UserAndProfile.Gender</div>
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="control-label">Birth Date</label>
                                            <div>
                                            @if (Model.UserAndProfile.BirthDate != null)
                                            {
                                                @Model.UserAndProfile.BirthDate.Value.ToString("dd/MM/yyyy")
                                            }
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>


<script>
    $(document).ready(function () {
        $("#BirthDate").datetimepicker({ format: "DD/MM/YYYY" });
    })
</script>