EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Controllers/ReportController.cs
﻿using System;
using EasyGasAdminWebsite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EasyGasAdminWebsite.Controllers
{

    [Authorize]
    public class ReportController : BaseController
    {
        public ReportController(UserManager<ApplicationUser> userManager, IHttpContextAccessor httpContextAccessor) : base(userManager, httpContextAccessor)
        {
        }

       

        

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult DatewiseReport()
        {
            return View();

        }

        public IActionResult TruckwiseReport()
        {
            return View();

        }


        //public async Task<Dictionary<int, VehicleLocationsViewModel>> GetVehicleLocations()
        //{
        //    int? branchId = await GetCurrentUserBranchId();
        //    int tenantId = await GetCurrentUserTenantId();

        //    Task<List<VehicleLocationsViewModel>> vehLocTask = _orderServices.GetVehicleLocations((int)tenantId, branchId);
        //    List<VehicleLocationsViewModel> vehList = await vehLocTask;



        //}
    }

}

EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Views/Report/DatewiseReport.cshtml
@model EasyGasAdminWebsite.Models.UserAndProfileModel
@addTagHelper *, EasyGasAdminWebsite
@{
    ViewData["Title"] = ViewBag.source + " Reports";
    EasyGasAdminWebsite.Models.ApiValidationErrors responseMsg = ViewBag.responseMsg;
}

<div class="content-wrapper">
    <section class="content-header">
        <h1>@ViewData["Title"]</h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="@Url.Action("Index", "Report")"><i class="fa fa-dashboard"></i>Reports</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>
    
</div>


EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Views/Report/Index.cshtml


@model EasyGasAdminWebsite.Models.UserAndProfileModel
@addTagHelper *, EasyGasAdminWebsite
@{
    ViewData["Title"] = ViewBag.source + " Reports";
    EasyGasAdminWebsite.Models.ApiValidationErrors responseMsg = ViewBag.responseMsg;

}


<style>

</style>
<div class="content-wrapper">
    <section class="content-header">
        <h1>@ViewData["Title"]</h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="@Url.Action("Index", "Report")"><i class="fa fa-dashboard"></i>Reports</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>
    <section class="content">

        <div class="row">

            <a href="@Url.Action("TruckwiseReport", "Report")">

                <div class="col-lg-3 col-xs-6">
                    <div class="small-box bg-orange">
                        <div class="inner">
                            <h4 style="text-align:center">Truckwise Report</h4>
                        </div>

                    </div>
                </div>


            </a>

            <a href="@Url.Action("DatewiseReport", "Report")">

                <div class="col-lg-3 col-xs-6">

                    <div class="small-box bg-blue">
                        <div class="inner">
                            <h4 style="text-align:center">Datewise Report</h4>
                        </div>

                    </div>
                </div>
            </a>

        </div>

    </section>

</div>







</div>



