EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EasyGasAdminWebsite.Services;
using Microsoft.Extensions.Options;
using EasyGasAdminWebsite.Configuration;
using EasyGasAdminWebsite.Models.OrderViewModels;
using EasyGasAdminWebsite.Models;
using System.Net;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;

namespace EasyGasAdminWebsite.Controllers
{
    [Authorize]
    public class VehiclesController : BaseController
    {
        private readonly IVehicleService _vehicleServices;
        private readonly IOptions<ApiSettings> _apiSettings;
        public VehiclesController(IVehicleService vehicleService, IOptions<ApiSettings> apiSettings, UserManager<ApplicationUser> userManager, IHttpContextAccessor httpContextAccessor) : base(userManager, httpContextAccessor)
        {
            _vehicleServices = vehicleService;
            _apiSettings = apiSettings;
        }

        public async Task<IActionResult> Index(int page)
        {
            int tenantId = await GetCurrentUserTenantId();
            int? branchId = await GetCurrentUserBranchId();
            List<VehicleModel> vehicleList = await _vehicleServices.GetListAsync(0, 10000, tenantId, branchId, null);
            ViewBag.vehicleList = vehicleList;
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            int tenantId = await GetCurrentUserTenantId();
            int? branchId = await GetCurrentUserBranchId();
            VehicleModel vehicle= new VehicleModel(){ IsActive = true};
            Models.VehicleViewModels.CreatePageModel createPageModel = await _vehicleServices.GetCreatePageModel(tenantId, branchId);
            //ViewBag.createPageModel = createPageModel;
            ViewBag.vehTypeSelList = new SelectList(createPageModel.VehicleTypeList, "Id", "Name");
            ViewBag.driverSelList = new SelectList(createPageModel.DriverList, "UserProfile.UserId", "UserProfile.FirstName");
            ViewBag.distributorSelList = new SelectList(createPageModel.DistributorList, "UserProfile.UserId", "UserProfile.FirstName");
            ApiValidationErrors responseMsg = new ApiValidationErrors() { };
            responseMsg.Err = new string[0];
            ViewBag.responseMsg = responseMsg;
            List<SelectListItem> statusList = new List<SelectListItem> {
                new SelectListItem { Text = "Yes", Value = "true"},
                new SelectListItem { Text = "No", Value = "false"}
            };
            ViewBag.statusList = statusList;
            ViewBag.source = "Create";
            return View(vehicle);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VehicleModel vehicle, string submitButton)
        {
            int tenantId = await GetCurrentUserTenantId();
            int? branchId = await GetCurrentUserBranchId();
            ApiValidationErrors responseMsg = new ApiValidationErrors { Err = new string[0] };
            if (ModelState.IsValid)
            {
                var result = await _vehicleServices.CreateVehicleAsync(vehicle);
                if (result.IsSuccessStatusCode)
                {
                    if (submitButton == "1")
                    {
                        return Redirect("Create");
                    }
                    else if (submitButton == "2")
                    {
                        return Redirect("Index");
                    }
                }
                else
                {
                    if (result.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var responseJson = await result.Content.ReadAsStringAsync();
                        responseMsg = JsonConvert.DeserializeObject<ApiValidationErrors>(responseJson);
                    }
                    if (responseMsg.Err == null)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                    else if (responseMsg.Err.Length == 0)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                }
            }
            ViewBag.responseMsg = responseMsg;
            Models.VehicleViewModels.CreatePageModel createPageModel = await _vehicleServices.GetCreatePageModel(tenantId, branchId);
            //ViewBag.createPageModel = createPageModel;
            ViewBag.vehTypeSelList = new SelectList(createPageModel.VehicleTypeList, "Id", "Name");
            ViewBag.driverSelList = new SelectList(createPageModel.DriverList, "UserProfile.UserId", "UserProfile.FirstName");
            ViewBag.distributorSelList = new SelectList(createPageModel.DistributorList, "UserProfile.UserId", "UserProfile.FirstName");
            List<SelectListItem> statusList = new List<SelectListItem> {
                new SelectListItem { Text = "Yes", Value = "true"},
                new SelectListItem { Text = "No", Value = "false"}
            };
            ViewBag.statusList = statusList;
            ViewBag.source = "Create";
            return View(vehicle);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            int tenantId = await GetCurrentUserTenantId();
            int? branchId = await GetCurrentUserBranchId();
            Models.VehicleViewModels.CreatePageModel createPageModel = await _vehicleServices.GetEditPageModel(id, tenantId, branchId);
            if (createPageModel.Vehicle == null)
            {
                throw new Exception("Page not found");
            }
            VehicleModel vehicle = createPageModel.Vehicle;
            ViewBag.createPageModel = createPageModel;
            ViewBag.vehTypeSelList = new SelectList(createPageModel.VehicleTypeList, "Id", "Name");
            ViewBag.driverSelList = new SelectList(createPageModel.DriverList, "UserProfile.UserId", "UserProfile.FirstName");
            ViewBag.distributorSelList = new SelectList(createPageModel.DistributorList, "UserProfile.UserId", "UserProfile.FirstName");
            ApiValidationErrors responseMsg = new ApiValidationErrors() { };
            responseMsg.Err = new string[0];
            ViewBag.responseMsg = responseMsg;
            List<SelectListItem> statusList = new List<SelectListItem> {
                new SelectListItem { Text = "Yes", Value = "true"},
                new SelectListItem { Text = "No", Value = "false"}
            };
            ViewBag.statusList = statusList;
            ViewBag.source = "Edit";
            return View("Create", vehicle);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VehicleModel vehicle, string submitButton)
        {
            int tenantId = await GetCurrentUserTenantId();
            int? branchId = await GetCurrentUserBranchId();
            ApiValidationErrors responseMsg = new ApiValidationErrors { Err = new string[0] };
            if (ModelState.IsValid)
            {
                var result = await _vehicleServices.UpdateVehicleAsync(vehicle);
                if (result.IsSuccessStatusCode)
                {
                    if (submitButton == "1")
                    {
                        return Redirect("Create");
                    }
                    else if (submitButton == "2")
                    {
                        return Redirect("Index");
                    }
                }
                else
                {
                    if (result.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var responseJson = await result.Content.ReadAsStringAsync();
                        responseMsg = JsonConvert.DeserializeObject<ApiValidationErrors>(responseJson);
                    }
                    if (responseMsg.Err == null)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                    else if (responseMsg.Err.Length == 0)
                    {
                        responseMsg.Err = new string[1] { "Some internal error has occured. Please try again." };
                    }
                }
            }
            ViewBag.responseMsg = responseMsg;
            Models.VehicleViewModels.CreatePageModel createPageModel = await _vehicleServices.GetCreatePageModel(tenantId, branchId);
            //ViewBag.createPageModel = createPageModel;
            ViewBag.vehTypeSelList = new SelectList(createPageModel.VehicleTypeList, "Id", "Name");
            ViewBag.driverSelList = new SelectList(createPageModel.DriverList, "UserProfile.UserId", "UserProfile.FirstName");
            ViewBag.distributorSelList = new SelectList(createPageModel.DistributorList, "UserProfile.UserId", "UserProfile.FirstName");
            List<SelectListItem> statusList = new List<SelectListItem> {
                new SelectListItem { Text = "Yes", Value = "true"},
                new SelectListItem { Text = "No", Value = "false"}
            };
            ViewBag.statusList = statusList;
            ViewBag.source = "Edit";
            return View("Create", vehicle);
        }
    }
}

EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Views/Vehicles/Create.cshtml
@model EasyGasAdminWebsite.Models.VehicleModel
@addTagHelper *, EasyGasAdminWebsite
@{
    ViewData["Title"] = ViewBag.source + " Vehicle";
    EasyGasAdminWebsite.Models.ApiValidationErrors responseMsg = ViewBag.responseMsg;
    SelectList vehTypeSelList = ViewBag.vehTypeSelList;
    SelectList driverSelList = ViewBag.driverSelList;
    SelectList distributorSelList = ViewBag.distributorSelList;
    List<SelectListItem> statusList = ViewBag.statusList;
}
<style>
   
</style>
<div class="content-wrapper">
    <section class="content-header">
        <h1>@ViewData["Title"]</h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="@Url.Action("Index", "Vehicles")"><i class="fa fa-dashboard"></i> Vehicles</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-6">
                <div id="create-order-box" class="box box-danger">
                    @using (Html.BeginForm())
                    {
                        <div class="box-body">
                            <div id="create-order" class="row">
                                <div class="col-md-12">
                                    @if (responseMsg.Err.Length > 0)
                                    {
                                        <div class="validation-summary-errors alert alert-danger-light">
                                            <p>Please correct the following errors</p>
                                            <ul class="validation-summary-errors">
                                                @foreach (string err in responseMsg.Err)
                                                {
                                                    <li>@err</li>
                                                }
                                            </ul>
                                        </div>
                                    }


                                    @Html.AntiForgeryToken()
                                    @Html.HiddenFor(model => model.Id, new { @id = "vehId" })

                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="RegNo" class="control-label"></label>
                                                @Html.EditorFor(model => model.RegNo, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.RegNo, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="DistributorId" class="control-label"></label>
                                                <select asp-for="DistributorId" asp-items="@distributorSelList" class="form-control">
                                                    <option value="">Select</option>
                                                </select>
                                                @Html.ValidationMessageFor(model => model.DistributorId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="TypeId" class="control-label"></label>
                                                <select asp-for="TypeId" asp-items="@vehTypeSelList" class="form-control">
                                                    <option value="">Select</option>
                                                </select>
                                                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="DriverId" class="control-label"></label>
                                                <select asp-for="DriverId" asp-items="@driverSelList" class="form-control">
                                                    <option value="">Select</option>
                                                </select>
                                                @Html.ValidationMessageFor(model => model.DriverId, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="DestinationLat" class="control-label"></label>
                                                @Html.EditorFor(model => model.DestinationLat, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.DestinationLat, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="DestinationLng" class="control-label"></label>
                                                @Html.EditorFor(model => model.DestinationLng, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.DestinationLng, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="IsActive" class="control-label"></label>
                                                <select asp-for="IsActive" asp-items="@statusList" class="form-control">
                                                </select>
                                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="row">
                                <div class="col-md-12">
                                    @if (ViewBag.source == "Edit")
                                    {
                                        <button class="btn btn-primary btn-lg" name="submitButton" value="2" style="margin-right: 10px;">Save</button>
                                    }
                                    else
                                    {
                                        <button class="btn btn-primary btn-lg" name="submitButton" value="1" style="margin-right: 10px;">Save and Create</button>
                                        <button class="btn btn-default btn-lg" name="submitButton" value="2">Save and Exit</button>
                                    }
                                </div>
                            </div>
                        </div>
                     }
                    </div>
            </div>
        </div>
    </section>
</div>



EasyGasAdmin Ebsite/src/EasyGasAdminWebsite/Views/Vehicles/Index.cshtml

@{
    ViewData["Title"] = "Vehicles";
    List<VehicleModel> vehiclesList = ViewBag.vehicleList;
}

<style>
    #filters {
        margin-left: 30px;
        display: inline-block;
    }

    #filters .form-group {
        max-width: 320px;
    }
    .select2-container {
        z-index: 99999 !important;
    }
    .popover .select2-container {
        width: 180px !important;
    }
    .select2-container .select2-selection--single {
        height: 32px;
    }
    .popover {
        max-width: 400px !important;
        min-width: 300px;
    }
    .customerName, .vehicleName { font-weight: 700; cursor: pointer;}
    #locations-updatetime {
        font-weight: bold;
    }

    #update-locations i {
        margin-right: 5px;
    }
</style>
<div class="content-wrapper">
    @*<section class="content-header">
        <h1>@ViewData["Title"]</h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Home", "Index")"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>*@
    <section class="content">
        <div class="row">
            <div class="col-xs-8">
                <div class="box box-danger">
                    <div class="box-header with-border">
                                <h3 class="box-title">Vehicles <a href="@Url.Action("Create")" style="margin-left: 10px;" class="btn btn-primary btn-sm"><i class="fa fa-plus" style="margin-right:5px;"></i> Create New</a></h3>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table id="vehicleList" class="table table-hover table-striped">
                                    <thead>
                                        <tr>
                                            <th>S No</th>
                                            <th>Reg No</th>
                                            <th>Type</th>
                                            <th>Destination</th>
                                            <th>Driver</th>
                                            <th>Distributor</th>
                                            <th>Status</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (VehicleModel item in vehiclesList)
                                        {
                                        
                                        <tr data-vehicle_id="@item.Id">
                                            <td></td>
                                            <td>@item.RegNo</td>
                                            <td>@item.TypeName</td>
                                            <td>@item.DestinationLat , @item.DestinationLng</td>
                                            <td>@item.DriverName</td>
                                            <td>@item.DistributorName</td>
                                            <td class="status">
                                                @if (item.IsActive)
                                                {
                                                    @:Active
                                                }
                                                else
                                                {
                                                    @:Inactive
                                                }
                                            </td>
                                            <td>
                                                <a class="btn btn-primary" href="@Url.Action("Edit", "Vehicles", new {id = item.Id })">Edit</a>
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
</div>

<script>
    var orderDataTable = $("#vehicleList").DataTable({
        'paging': true,
        'lengthChange': true,
        'searching': true,
        'ordering': true,
        'info': true,
        'autoWidth': true,
        'columnDefs': [{ orderable: false, targets: [-1] }],
        'language': {
            'emptyTable': 'No vehicles found.'
        },
        "fnRowCallback": function (nRow, aData, iDisplayIndex) {
            $("td:first", nRow).html(iDisplayIndex + 1);
            return nRow;
        },
    })

   
</script>